name: Deploy to EC2

on:
  push:
    branches:
      - main   # Change this to your branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # Install backend dependencies
      - name: Install backend dependencies
        run: |
          cd backend
          npm install

      # Install frontend dependencies
      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install
          npm run build

      # Deploy to EC2
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/website-course-node
            git pull origin main
            cd backend && npm install
            pm2 restart backend || pm2 start server.js --name backend
            cd ../frontend && npm install && npm run build
            pm2 restart frontend || pm2 start "npx serve -s build -l 3000" --name frontend
